%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear;
clc;
close all;
%--------------------------------------------------------------------------
dirs = [...
    "core/", ...
    "debug/", ...
    "init/", ...
    "integrals/", ...
    "quad/", ...
    "wetdry/", ...
    "Plot/", ...
    "Plot/T01 - Grilli/", ...
    "Plot/T01 - Grilli/DATA/0.10/C3/", ...
    "Plot/T01 - Grilli/DATA/0.15/C3/", ...
    "Plot/T01 - Grilli/DATA/0.20/C0/", ...
    "Plot/T01 - Grilli/DATA/0.20/C1/", ...
    "Plot/T01 - Grilli/DATA/0.20/C2/", ...
    "Plot/T01 - Grilli/DATA/0.20/C3/", ...
    "Plot/T01 - Grilli/DATA/0.25/C3/", ...
    "Plot/T01 - Grilli/FRAMES/", ...
    "Plot/T03 - Composite beach (NOAA)/", ...
    "Plot/T03 - Composite beach (NOAA)/DATA/0.039/", ...
    "Plot/T03 - Composite beach (NOAA)/DATA/0.264/", ...
    "Plot/T03 - Composite beach (NOAA)/FRAMES/", ...
    "Plot/T04 - Reflection of shoaling waves/", ...
    "Plot/T04 - Reflection of shoaling waves/DATA/0.1000/", ...
    "Plot/T04 - Reflection of shoaling waves/DATA/0.1834/", ...
    "Plot/T04 - Reflection of shoaling waves/FRAMES/", ...
    "Plot/T06 - Head-on-colission/", ...
    "Plot/T06 - Head-on-colission/DATA/0.96/", ...
    "Plot/T06 - Head-on-colission/DATA/0.21/", ...
    "Plot/T06 - Head-on-colission/FRAMES/", ...
    "Plot/T07 - Wall/", ...
    "Plot/T07 - Wall/DATA/0.96/", ...
    "Plot/T07 - Wall/DATA/0.21/", ...
    "Plot/T07 - Wall/FRAMES/", ...
    "Plot/T08 - Overtaking colission/", ...
    "Plot/T08 - Overtaking colission/DATA/", ...
    "Plot/T08 - Overtaking colission/FRAMES/", ...
    "Plot/T09 - Breakup of a Gaussian hump/", ...
    "Plot/T09 - Breakup of a Gaussian hump/DATA/01/", ...
    "Plot/T09 - Breakup of a Gaussian hump/DATA/20/", ...
    "Plot/T09 - Breakup of a Gaussian hump/FRAMES/", ...
    "Plot/T10 - Dispersive dam-break/", ...
    "Plot/T10 - Dispersive dam-break/DATA/", ...
    "Plot/T10 - Dispersive dam-break/FRAMES/", ...
    "Plot/T11 - Reversibility check/", ...
    "Plot/T11 - Reversibility check/DATA/C0/", ...
    "Plot/T11 - Reversibility check/DATA/C3/", ...
    "Plot/T11 - Reversibility check/FRAMES/", ...
    "Plot/T12 - Carrier and Greenspan/", ...
    "Plot/T12 - Carrier and Greenspan/DATA/per/", ...
    "Plot/T12 - Carrier and Greenspan/DATA/trans/", ...
    "Plot/T13 - Oscillating lake/", ...
    "Plot/T13 - Oscillating lake/DATA (-06)/", ...
    "Plot/T13 - Oscillating lake/DATA (-12)/", ...
    "Plot/T13 - Oscillating lake/FRAMES/", ...
    "Plot/T14 - Lake at rest/", ...
    "Plot/T14 - Lake at rest/DATA/", ...
    "Plot/T14 - Lake at rest/FRAMES/", ...
    "Plot/T15 - Synolakis/", ...
    "Plot/T15 - Synolakis/DATA/0.019/", ...
    "Plot/T15 - Synolakis/DATA/0.040/", ...
    "Plot/T15 - Synolakis/FRAMES/"];
for i = 1:numel(dirs)
    folder = dirs(1, i);
    if ~isfolder(folder)
        mkdir(folder);
    end
    addpath(folder);
end
%--------------------------------------------------------------------------
fn = fieldnames(get(groot, 'factory'));
fc = find(contains(fn, 'Interpreter'));
for i = 1:size(fc, 1)
    set(groot, strrep(fn{fc(i, 1)}, 'factory', 'default'), 'latex');
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
p         = 1;
test      = 15;
data      = setdata(test, 0);
g         = MSH(data.xv, p);
drytol    = 1e-06;
velcutoff = 1e-04;
vellim    = 1;
itype     = 1;     % 0: uhaina: interpolation
                   % 1: my:     projection
CFL       = 0.05;  % CFL./(2.*p+1);
penParam  = 1000;
run       = 1;
%--------------------------------------------------------------------------
g.CFL     = CFL;
g.t       = 0;
g.nit     = 0;
g.test    = test;
g.data    = data;
g         = initsol    (g, itype, drytol, velcutoff, vellim);
g         = initsoldisp(g);
%--------------------------------------------------------------------------
if run
    switch test
        case {1, 2, 3, 4, 5}
            obj = PlotA1(g);
        case {6, 7, 8, 9, 10, 11, 12, 13, 14, 15}
            obj = PlotA2(g);
        otherwise
            return
    end
    while g.t < g.data.tend
        [g, obj] = ADVt(g, obj, penParam);
    end
else
    switch test %#ok<UNRCH>
        case 1
            PlotT01C(g, [0, 0]); % DONE
        case 2
        case 3
            PlotT03C(g, [0, 0]);
        case 4
            PlotT04C(g, [0, 0]); % DONE
        case 5
        case {6, 7}
            PlotT06C(g, [0, 0]); % DONE
        case 8
            PlotT08C(g, [0, 0]); % DONE
        case 9
            PlotT09C(g, [0, 0]); % DONE
        case 10
            PlotT10C(g, [0, 0]); % DONE
        case 11
            PlotT11C(g, [0, 0]); % DONE
        case 12
        case 13
            PlotT13C(g, [0, 0]); % DONE
        case 14
        case 15
            PlotT15C(g, [0, 0]); % DONE
        otherwise
            return
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%