%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear;
clc;
close all;
%--------------------------------------------------------------------------
dirs = [...
    "core/", ...
    "core/spinit/src", ... https://www.mathworks.com/matlabcentral/fileexchange/30293-spinit?s_tid=srchtitle
    "core/QuadTools", ... https://www.mathworks.com/matlabcentral/fileexchange/72378-quadtools
    "debug/", ...
    "init/", ...
    "integrals/", ...
    "quad/", ...
    "wetdry/", ...
    "Plot/", ...
    "Plot/linspecer/", ...
    "Plot/S0/T0 - Convergence (GN)/", ...
    "Plot/S0/T0 - Convergence (GN)/DATA/", ...
    "Plot/S0/T0 - Convergence (SW)/", ...
    "Plot/S0/T0 - Convergence (SW)/DATA/", ...
    "Plot/S0/T1 - Wave generation/", ...
    "Plot/S0/T1 - Wave generation/DATA/", ...
    "Plot/S1/T1 - Lake at rest/", ...
    "Plot/S1/T1 - Lake at rest/DATA/", ...
    "Plot/S1/T2 - Drying of a lake/", ...
    "Plot/S1/T2 - Drying of a lake/DATA/", ...
    "Plot/S1/T3 - Oscillating lake/", ...
    "Plot/S1/T3 - Oscillating lake/DATA/", ...
    "Plot/S2/T1 - Head-on-colission/", ...
    "Plot/S2/T1 - Head-on-colission/DATA/0.21/", ...
    "Plot/S2/T1 - Head-on-colission/DATA/0.96/", ...
    "Plot/S2/T2 - Wall/", ...
    "Plot/S2/T2 - Wall/DATA/0.21/", ...
    "Plot/S2/T2 - Wall/DATA/0.96/", ...
    "Plot/S2/T3 - Overtaking colission/", ...
    "Plot/S2/T3 - Overtaking colission/DATA/", ...
    "Plot/S2/T4 - Breakup of a Gaussian hump/", ...
    "Plot/S2/T4 - Breakup of a Gaussian hump/DATA/01/", ...
    "Plot/S2/T4 - Breakup of a Gaussian hump/DATA/20/", ...
    "Plot/S2/T5 - Dispersive dam-break/", ...
    "Plot/S2/T5 - Dispersive dam-break/DATA/", ...
    "Plot/S3/T1 - Grilli/", ...
    "Plot/S3/T1 - Grilli/DATA/0.20/C0/", ...
    "Plot/S3/T1 - Grilli/DATA/0.10/C3/", ...
    "Plot/S3/T1 - Grilli/DATA/0.15/C3/", ...
    "Plot/S3/T1 - Grilli/DATA/0.20/C3/", ...
    "Plot/S3/T1 - Grilli/DATA/0.25/C3/", ...
    "Plot/S3/T2 - Reversibility check/", ...
    "Plot/S3/T2 - Reversibility check/DATA/C0/", ...
    "Plot/S3/T2 - Reversibility check/DATA/C3/", ...
    "Plot/S3/T3 - Reflection of shoaling waves/", ...
    "Plot/S3/T3 - Reflection of shoaling waves/DATA/0.1000/", ...
    "Plot/S3/T3 - Reflection of shoaling waves/DATA/0.1834/", ...
    "Plot/S3/T4 - Synolakis/", ...
    "Plot/S3/T4 - Synolakis/DATA/0.019/", ...
    "Plot/S3/T4 - Synolakis/DATA/0.040/", ...
    "Plot/S3/T5 - Submerged bar/", ...
    "Plot/S3/T5 - Submerged bar/DATA/", ...
    "Plot/S3/T6 - Wave overtopping over a seawall/", ...
    "Plot/S3/T6 - Wave overtopping over a seawall/DATA/"];
for i = 1:numel(dirs)
    folder = dirs(1, i);
    if ~isfolder(folder)
        mkdir(folder);
    end
    addpath(folder);
end
%--------------------------------------------------------------------------
fn = fieldnames(get(groot, 'factory'));
fc = find(contains(fn, 'Interpreter'));
for i = 1:size(fc, 1)
    set(groot, strrep(fn{fc(i, 1)}, 'factory', 'default'), 'latex');
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
p         = 1;
test      = 11;
run       = 0;
%--------------------------------------------------------------------------
data      = setdata(test, 0);
g         = MSH(data.xv, p);
drytol    = 1.0e-02;
velcutoff = drytol;
vellim    = 1;
itype     = 0; % 0: uhaina: interpolation
               % 1: my:     projection
CFL       = 3./(4.*(2.*p+1));
theta     =-1;
penParam  = 1000;
%--------------------------------------------------------------------------
g.CFL     = CFL;
g.t       = 0;
g.nit     = 0;
g.test    = test;
g.data    = data;
dispers   = g.data.dispers;
g         = initsol(g, itype, drytol, velcutoff, vellim, data.wetdry);
if dispers
    g = initsoldisp(g, theta, penParam);
end
%--------------------------------------------------------------------------
if run
    obj = PlotA1(g);
    while g.t < g.data.tend
        [g, obj] = ADVt(g, obj, penParam);
    end
else
    switch test %#ok<UNRCH>
        case {1, 2}
            PlotS0T0(g, [0, 0]);
        case 3
        case 4
        case 5
        case 6
        case {7, 8}
            PlotS2T1(g, [0, 0]);
        case 9
            PlotS2T3(g, [0, 0]);
        case 10
        case 11
            PlotS2T5(g, [1, 0]);
        case 12
            PlotS3T1(g, [0, 0]);
        case 13
        case 14
            PlotS3T3(g, [1, 0]);
        case 15
        case 16
        case 17
        otherwise
            return
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%