function [] = PlotX1(xlim, ylim, xtick, ytick, xticklabel, yticklabel, xtitle, ytitle)
set(gca, ...
    'Box', 'on', ...
    'Clipping', 'on', ...
    'FontSize', 19.5, ...
    'Layer', 'top', ...
    'TickLabelInterpreter', 'latex', ...
    'XLim', xlim, ...
    'YLim', ylim, ...
    'XTick', xtick, ...
    'YTick', ytick, ...
    'XTickLabel', xticklabel, ...
    'YTickLabel', yticklabel, ...
    'XMinorTick', 'on', ...
    'YMinorTick', 'on');
axis square;
xlabel(xtitle, 'Fontsize', 25); xtickangle(0);
ylabel(ytitle, 'Fontsize', 25); ytickangle(0);
end