function [] = PlotX2(P, legendlabel, location, numcols)
legend(cat(2, P{1, :}), legendlabel, ...
    'AutoUpdate', 'off', ...
    'FontSize', 20.5, ...
    'Location', location, ...
    'NumColumns', numcols);
end